### ISSUE TITLE
Builds for multiple versions

### ISSUE THREAD

**Issue by jooaf** [FMotalleb/nu_plugin_clipboard#13]
Hello, I hope you all are doing well :) ! 

So I have noticed that this plugin only works with the most up to date Nushell version (0.97.1 as of posting this issue) and version 0.91.0 from [here](https://crates.io/crates/nu_plugin_clipboard/versions). If it is possible, could this plugin be used to support 0.92.0 to 0.97.0? i would be happy to help with this by the way since I use this plugin a lot.

**Comment by fmotalleb** [comment]
well, since I am terrible at maintenance I don't use release tags for my nu plugins because I mostly develop them for my use cases, anyway, you can see commit messages for example you can use commit
https://github.com/FMotalleb/nu_plugin_clipboard/commit/98d71029ca5b7a722fbe6992e9700f800ce7f802
for v0.91
well you need to clone this repo and then use 
```bash
git checkout 98d71029ca5b7a722fbe6992e9700f800ce7f802
```
anyway Since the last release, I've added an action that updates cargo.io and this won't happen in the feature

**Comment by jooaf** [comment]
got it makes sense! cool i'll just clone the repo checkout at different sha to build the plugin. thanks so much for making this tool :)
