### ISSUE TITLE
(crates.io) "Plugin failed to decode", nu 0.90.1

### ISSUE THREAD

**Issue by LeoniePhiline** [FMotalleb/nu_plugin_clipboard#3]
```
~> clipboard paste
Error:   × Plugin failed to decode
  help: array had incorrect length, expected 3
```

**Comment by fmotalleb** [comment]
Have you tried updating the plugin?

**Comment by LeoniePhiline** [comment]
Hi, thanks for your response!

It’s a fresh, first-time install. 

Is it possible that the latest version has not yet been released to crates.io?

**Comment by fmotalleb** [comment]
They are updated now.
But since I don't update my crates often, the recommended approach would be to clone the repository and build the plugin from the source code. You can also consider using [`nupm`](https://github.com/nushell/nupm) to install plugins, especially those that require build time configuration. (for example clipboard plugin has custom `nupm` install script)

**Comment by LeoniePhiline** [comment]
Thanks! Being new to nu, I had chosen the installation path I was the most familiar with. I see that nupm is going to be "the right way" going forward.


Thank you very much for your response, release, and your fantastic plugins!
